name: Terraform Installation

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Install Terraform
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
          terraform_version: ">= 1.2.0"

      - name: Checkout code
        uses: actions/checkout@v2   

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        run: terraform plan 
        

      - name: Terraform Apply
        run: terraform apply 